apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-ssl
spec:
  tls:
  - hosts:
    - kube-test.com # (1)
    secretName: kube-test-secret # (2)
  rules:
  - host: kube-test.com
    http:
      paths:
      - paths: /
      - backend:
          serviceName: service1
          servicePort: 80
          

    # (1) 호스트 이름을 kube-test.com으로 설정했다.
    # (2) 앞서 만든 secretName인 kube-test.com을 설정했다.