apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-nodeaffinity-pod
spec:
  containers:
  - name: kubernetes-nodeaffinity-pod
    image: arisu1000/simple-container-app:latest
    ports:
    - containerPort: 8080
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: beta.kubernetes.io/os
            operator: In
            values:
            - linux
            - window
          - key: disktype
            operator: Exists
          - key: core
            operator: Gt  
            values: 
            - "4"
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 10
        preference:
          matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - worker-node01

            # (1)operator값은 .key가 만족할 조건을 기재해주는 부분이다.
            # IN : VALUES 필드에 설정한 값중 레이블에 있는 값과 일치하는것이 한개라도 있는지 확인한다.
            # Notln : 필드에 있는 값 모두와 맞는지 확인한다.
            # Exists : 다른 조건을 모두 무시하고 key필드값이 있는지만 확인한다.
            # DoesNotExist key필드값이 없는지만 확인한다.
            # Gt : values 필드에 설정된 값보다 큰 숫자형 데이터인지 확인하며, 값이 하나만 있어야한다.
            # Lt : values 필드에 설정된 값보다 작은 숫자형 데이터인지 확인하며, 값이 하나만 있어야한다.