apiVersion: v1
kind: Pod
metadata:
  name: pod-env
  labels:
    app: pod-env
spec:
  containers:
  - name: pod-env
    image: arisu1000/simple-container-app:latest
    ports:
    - containerPort: 8080
    env: 
    - name: test-env  # (1)
      value: "testenv"
    - name: HOSTNAME  # (2)
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME  # (3)
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_IP  # (4)
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: CPU_REQUEST # (5)
      valueFrom:
        resourceFieldRef:
          containerName: pod-env
          resource: requests.cpu
    - name: CPU_LIMIT # (6)
      valueFrom:
        resourceFieldRef:
          containerName: pod-env
          resource: limits.cpu