apiVersion: v1
kind: Secret
metadata:
  name: user-pass-yaml
type: Opaque
data:
  username: //51AHMAZQByAG4AYQBtAGUADQAKAA==
  password: //5wAGEAcwBzAHcAbwByAGQADQAKAA==

#       type 필드값을 3가지 설정할 수 있다. 
#       Opaque이란? 키-값 형식으로 임의의 데이터를 설정한다.
#       kubernetes.io/service-account-token : 쿠버네티스 인증 ㅌ큰을 저장
#       kubernetes.io/dockerconfigjson : 도커 저장소 인증 정보를 저장
#       kubernetes.io/tls : TLS 인증서를 저장 